import random

GERMAN_NAMES = [
    "Gutenberg",
    "Beethoven",
    "Hildegard",
    "Wolfgang",
    "Lieselotte",
    "Dietrich",
    "Brunhilde",
    "Siegfried",
    "Gertrude",
    "Friedrich",
    "Hannelore",
    "Reinhardt",
    "Waltraud",
    "Helmut",
    "Edelweiss",
    "Gretchen",
    "Manfred",
    "Ingeborg",
    "Albrecht",
    "Kriemhild",
    "Engelbert",
    "Rosamund",
    "Gottfried",
    "Mechthild",
    "Ruprecht",
    "Adelheid",
    "Bernhard",
    "Elfriede",
    "Karlheinz",
    "Dagmar",
    "Winfried",
    "Kunigunde",
    "Baldur",
    "Walburga",
    "Dieter",
    "Irmgard",
    "Hubertus",
    "Sigrid",
    "Volkmar",
    "Anneliese",
    "Burkhard",
    "Heidrun",
    "Norbert",
    "Roswitha",
    "Hartmut",
    "Konstanze",
    "Erhardt",
    "Brunnhilde",
    "Bob",
]


def generate_kick_name(existing_names):
    available = [f"AI: {n}" for n in GERMAN_NAMES if f"AI: {n}" not in existing_names]
    return random.choice(available)
