# Generated by Django 5.2.10 on 2026-01-24 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=32, unique=True)),
                ('bpm', models.PositiveSmallIntegerField()),
                ('kick_sample', models.CharField(max_length=32)),
                ('kick_len', models.FloatField()),
                ('kick_dist_amt', models.FloatField()),
                ('kick_ott_amt', models.FloatField()),
                ('noise_sample', models.CharField(max_length=32)),
                ('noise_low_pass_freq', models.FloatField()),
                ('noise_high_pass_freq', models.FloatField()),
                ('noise_dist_amt', models.FloatField()),
                ('reverb_sample', models.CharField(max_length=32)),
                ('reverb_low_pass_freq', models.FloatField()),
                ('reverb_high_pass_freq', models.FloatField()),
                ('reverb_phaser_amt', models.FloatField()),
                ('master_ott_amt', models.FloatField()),
                ('master_dist_amt', models.FloatField()),
                ('master_limiter_amt', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['preset_name'],
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=32)),
                ('bpm', models.PositiveSmallIntegerField()),
                ('kick_sample', models.CharField(max_length=32)),
                ('kick_len', models.FloatField()),
                ('kick_dist_amt', models.FloatField()),
                ('kick_ott_amt', models.FloatField()),
                ('noise_sample', models.CharField(max_length=32)),
                ('noise_low_pass_freq', models.FloatField()),
                ('noise_high_pass_freq', models.FloatField()),
                ('noise_dist_amt', models.FloatField()),
                ('reverb_sample', models.CharField(max_length=32)),
                ('reverb_low_pass_freq', models.FloatField()),
                ('reverb_high_pass_freq', models.FloatField()),
                ('reverb_phaser_amt', models.FloatField()),
                ('master_ott_amt', models.FloatField()),
                ('master_dist_amt', models.FloatField()),
                ('master_limiter_amt', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['preset_name'],
                'unique_together': {('user', 'preset_name')},
            },
        ),
    ]
