# Generated by Django 5.2.10 on 2026-01-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preset',
            old_name='noise_dist_amt',
            new_name='noise_volume',
        ),
        migrations.RenameField(
            model_name='sharedpreset',
            old_name='noise_dist_amt',
            new_name='noise_volume',
        ),
    ]
