# Generated by Django 5.2.10 on 2026-01-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0002_rename_noise_dist_to_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preset',
            old_name='reverb_phaser_amt',
            new_name='reverb_volume',
        ),
        migrations.RenameField(
            model_name='sharedpreset',
            old_name='reverb_phaser_amt',
            new_name='reverb_volume',
        ),
    ]
