# Generated by Django 5.2.10 on 2026-01-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0003_rename_phaser_to_volume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedPreset',
        ),
        migrations.AddField(
            model_name='preset',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
